version: '3.8'
services:
  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'abc123'
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build:
      context: ./
      target: rails-builder
    stdin_open: true
    tty: true
    ports:
      - "${PORT:-3000}:5000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      REDIS_URL: redis://redis:6379
    restart: always
volumes:
  pg-data:
