version: '3.8'
services:
  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ./
      target: rails-builder
    stdin_open: true
    tty: true
    ports:
      - "3000:5000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    environment:
      BINDING: 0.0.0.0
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/
      PORT: 5000
      REDIS_URL: redis://redis:6379/number_two_dev
    restart: always
volumes:
  pg-data:
