version: '3.8'

services:
  web:
    build: .
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p455w0rd
