default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>